<a href="https://colab.research.google.com/github/kpakshaya123/Sprint1-COLAB-/blob/main/Akshaya_(Sprint1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***CAR SALES DATASET***

In [63]:
import pandas as pd

In [64]:
df=pd.read_csv('Car_Sales DataSet.csv')

In [65]:
df.head()

    Make Model        Year   Sales
0  acura   ILX         NaN  13.900
1  acura   ILX  Acura\nILX  13.414
2  acura   ILX        2021  14.685
3  acura   ILX        13.9  11.273
4  acura   ILX        2020  11.757

In [ ]:
df.shape[0]

93

REMOVE DUPLICATES

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.shape[0]

93

In [ ]:
df.shape

(93, 4)

In [ ]:
df.describe()

              Year      Sales
count    93.000000   93.00000
mean   2009.505376   85.82200
std       9.101629  165.24466
min    1991.000000    0.00000
25%    2004.000000   10.15300
50%    2012.000000   30.11700
75%    2017.000000   57.94800
max    2021.000000  884.00000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 2 to 212
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Make    93 non-null     object
 1   Model   93 non-null     object
 2   Year    93 non-null     float64
 3   Sales   93 non-null     float64
dtypes: float64(2), object(2)
memory usage: 3.6+ KB

*Remove* Rows Which has Missing Values

In [ ]:
df=df.dropna()

Replace The Number By String("BMW")

In [ ]:
df['Model']=df['Model'].apply (lambda x:x if str(x).isalpha() else "BMW")

In [ ]:
df.head(200)

           Make   Model                Year   Sales
1         acura     ILX          Acura\nILX  13.414
2         acura     ILX                2021  14.685
3         acura     ILX                13.9  11.273
4         acura     ILX                2020  11.757
5         acura     ILX              13.414  14.597
..          ...     ...                 ...     ...
210  alfa-romeo     BMW                1995   1.721
211  alfa-romeo     BMW                 414   2.155
212  alfa-romeo     BMW                1994   1.549
213  alfa-romeo     BMW                 357   0.000
223  alfa-romeo  Milano  Alfa Romeo\nMilano   5.000

[198 rows x 4 columns]

Handling Invalid Values in Year Column

1)Convert the Column to Numeric Value

In [ ]:
df['Year']=pd.to_numeric(df['Year'] ,errors="coerce")

2)Invalid Year values are replaced with NaN.

In [ ]:
df.loc[df['Year'] < 1000, 'Year'] = pd.NA

3)Rows where the Year value is missing (NaN) are removed.

In [ ]:
df=df.dropna(subset=['Year'])

4)It keeps only rows where the Year is a whole number and removes decimal values.

In [ ]:
df=df[df['Year']%1==0]

After cleaning, we check the dataset to confirm it is clean.

Shows missing values count in each column.

In [ ]:
df.isnull().sum()

Make     0
Model    0
Year     0
Sales    0
dtype: int64

In [ ]:
df['Year'].unique()

array([2021., 2020., 2019., 2018., 2016., 2015., 2014., 2013., 2012.,
       2011., 2017., 2007., 2006., 2005., 2004., 2003., 2002., 2010.,
       2009., 2008., 1996., 1995., 1994., 1997., 1993., 1992., 2001.,
       2000., 1999., 1991.])

In [ ]:
df['Model'].unique()

array(['ILX', 'TSX', 'TLX', 'RLX', 'NSX', 'RDX', 'MDX', 'ZDX', 'CL', 'TL',
       'RL', 'RSX', 'Vigor', 'Legend', 'SLX', 'Spider', 'BMW'],
      dtype=object)

In [ ]:
df.shape

(93, 4)

In [ ]:
df.dtypes

Make      object
Model     object
Year     float64
Sales    float64
dtype: object

In [ ]:
df=df.drop_duplicates()

In [ ]:
df.shape

(93, 4)

Cleaned Dataset Save in a CSV file

In [ ]:
df.to_csv('Cleaned Car_DataSet.csv', index= False)